# Generated by Django 5.1.2 on 2024-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='opening_time_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='opening_time_to',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
